#!/usr/bin/env bash
#
# Publish the website in the given directory to the webhost using rsync, overwriting the
# destination to exactly match the local copy.
set -o errexit -o nounset -o pipefail

USER="$(<"${HOME}/.certs/webhost.username")"
declare -r USER

declare -r WEBSITE="${1:-}"

if [[ -z "${WEBSITE}" ]]; then
  echo >&2 "Usage: $0 <website>"
  exit 1
fi

GIT_BRANCH="$(git symbolic-ref --short HEAD)"
declare -r GIT_BRANCH

branch_dir="${WEBSITE}"
if [[ "${GIT_BRANCH}" != "master" ]];then
  branch_dir="${WEBSITE}/branches/${GIT_BRANCH}"
fi

echo >&2 "Publishing [${WEBSITE}]"

echo >&2 "Destination [${USER}@${WEBSITE}:/home/${USER}/${branch_dir}/]"

rsync \
    --checksum \
    --compress \
    --delay-updates \
    --delete \
    --delete-after \
    --force \
    --human-readable \
    --links \
    --perms \
    --progress \
    --recursive \
    --safe-links \
    --stats \
    -n \
    --relative \
    "./${WEBSITE}/" \
    "${USER}@${WEBSITE}:/home/${USER}/${branch_dir}/"

echo >&2 "Done!"

